### ISSUE TITLE
Demo kinda works

### ISSUE THREAD

**Issue by LukeXF** [speakeasyjs/speakeasy#96]
[link](https://sedemo-mktb.rhcloud.com/)

First when I enter in a code to verify and then the generated token doesn't actually update (event though the countdown works and it says "updated".

I've also seen that that it just doesn't work at all with the right code?
<img width="720" alt="screen shot 2017-10-04 at 02 07 20" src="https://user-images.githubusercontent.com/6208873/31155796-bdacbd70-a8a8-11e7-8b6c-19e4bbe9a93e.png">

**Comment by Creativa2** [comment]
I met this problem too. My authenticator shows the previous token not the actual. (I checked this with console logs.)  At server start the first token is valid but then the second one not refresshing and after that there is a gap between the previous and the actual token.

**Comment by LukeXF** [comment]
I've noticed refreshing the page generates the right token (you just got to keep refreshing the page). I think Speakeasy is a great project, but if the demo doesn't work then it not going to attract new people to the project.

**Comment by LukeXF** [comment]
Demo is now altogether down. `Service Unavailable` it's been like that since last night.

**Comment by markbao** [comment]
Unfortunately, Red Hat discontinued their free hosting offering a few days ago. I'm working on getting it back online.

I think the issue here is that a request for a new token only updates if the system time's seconds is at :00 or :30. So if it is time 00:00:00 and the system time is fast by 5 seconds, and it asks for a second token at what it thinks is 00:00:30 but is actually 00:00:25, then it still has the old token for the next 25 seconds. Not sure if this is the cause, but it's the most plausible thing that comes to mind. I suggest using https://time.is/ to check if your clock is exactly set to official time.

I'll try to get the demo back online and see if it works.

**Comment by LukeXF** [comment]
If you want are looking at hosting the project then I don't mind putting it on one of my own Digital Ocean Droplets if you have the demo code on GitHub? I'm more than happy to help contribute to this project as it's helped me a lot in getting 2FA working.

Also I check out what you sent me, turns out even though my Macbook's time is synced to Apple's servers - it was over 45 seconds out haha. Synced it back again, so hopefully we will see an improvement.

**Comment by markbao** [comment]
Thank you for the offer! Really appreciate it. I’ll look into what the best options are and will let you know.

That definitely would result in the mismatched times. Let us know how it goes. In the meantime I’ll keep this issue open until the demo is back online.

**Comment by LukeXF** [comment]
Not had a problem since I fixed my mac's timing. 

How did the search for hosting go? Let me know if you want me to put up the demo, shouldn't take any time away from you.

**Comment by Hereward** [comment]
The demo project link is still not working. The package looks very interesting but not sure if I should invest time into it there is not a working demo?

**Comment by wairton** [comment]
@Hereward  It is possible to run the demo locally, just clone https://github.com/speakeasyjs/speakeasy-demo then run `npm install` and `npm start`. A local version will be available at localhost:8081. I know it doesn't solve your problem but it helps

**Comment by Hereward** [comment]
Thanks :)
